### ISSUE TITLE
Trocar dependencia request por got

### ISSUE THREAD

**Issue by luanmuniz** [alligo/consul-tls#1]
O request é muito grande e tem vários problemas de memory leak. `got` é uma opção melhor e estamos usando ele em vários outros modulos, então não precisa de mais um modulo para o mesmo fundamento

**Comment by fititnt** [comment]
Na pratica, estava pensando em mais tarde até trocar isso pra usar http.request puro. E sim, o Request instala até a pia da cozinha, e o uso dele aqui meio simples demais
