### ISSUE TITLE
Erro não está sendo gerado quando alguma chave não existe no Consul

### ISSUE THREAD

**Issue by bcdonadio** [alligo/consul-tls#4]
Ao executar uma operação get e as chaves de cert/key não existem no consul, o script deveria terminar com uma mensagem de erro e código de retorno igual a 1, mas nenhuma mensagem de erro é exibida e o status code vem igual a 0.

``` bash
root@cache-html1:/opt/consul-tls# node /opt/consul-tls/index.js get http://consul.service.consul:8500 homolog.zimp.me /etc/pki/tls/certs/homolog.zimp.me.crt /etc/pki/tls/private/homolog.zimp.me.key
root@cache-html1:/opt/consul-tls# echo $?
0
root@cache-html1:/opt/consul-tls#
```

**Comment by luanmuniz** [comment]
Resolvido em 9f29a874f67e3795acaf64a75edad281f263e964
